def create_seats():
    
    seats = {
                '1A': { 'S': 'None'},
                '1B': {'S': 'None'},
                '1C': {'S': 'None'},
                '1D': {'S': 'None'},
                '1E': {'S': 'None'},
                '1F': {'S': 'None'},
                '2A': { 'S': 'None'},
                '2B': {'S': 'None'},
                '2C': {'S': 'None'},
                '2D': {'S': 'None'},
                '2E': {'S': 'None'},
                '2F': {'S': 'None'},
                '3A': { 'S': 'None'},
                '3B': {'S': 'None'},
                '3C': {'S': 'None'},
                '3D': {'S': 'None'},
                '3E': {'S': 'None'},
                '3F': {'S': 'None'},
                '4A': { 'S': 'None'},
                '4B': {'S': 'None'},
                '4C': {'S': 'None'},
                '4D': {'S': 'None'},
                '4E': {'S': 'None'},
                '4F': {'S': 'None'},
                '5A': { 'S': 'None'},
                '5B': {'S': 'None'},
                '5C': {'S': 'None'},
                '5D': {'S': 'None'},
                '5E': {'S': 'None'},
                '5F': {'S': 'None'},
                '6A': { 'S': 'None'},
                '6B': {'S': 'None'},
                '6C': {'S': 'None'},
                '6D': {'S': 'None'},
                '6E': {'S': 'None'},
                '6F': {'S': 'None'},
                '7A': { 'S': 'None'},
                '7B': {'S': 'None'},
                '7C': {'S': 'None'},
                '7D': {'S': 'None'},
                '7E': {'S': 'None'},
                '7F': {'S': 'None'},
                '8A': { 'S': 'None'},
                '8B': {'S': 'None'},
                '8C': {'S': 'None'},
                '8D': {'S': 'None'},
                '8E': {'S': 'None'},
                '8F': {'S': 'None'},
                '9A': { 'S': 'None'},
                '9B': {'S': 'None'},
                '9C': {'S': 'None'},
                '9D': {'S': 'None'},
                '9E': {'S': 'None'},
                '9F': {'S': 'None'},
                '10A': { 'S': 'None'},
                '10B': {'S': 'None'},
                '10C': {'S': 'None'},
                '10D': {'S': 'None'},
                '10E': {'S': 'None'},
                '10F': {'S': 'None'}
    }  
    return seats